name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tutorials:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install packages
      run: |
        sudo apt-get install -y rename
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install jupyter pytest xgi==0.10
        python -m pip list

    - name: Prepare tutorial notebooks
      run: |
        # go into tutorial location
        cd siamds2025
        # convert each notebook into a python file
        jupyter nbconvert --to script *.ipynb
        # rename the files so they are found by pytest: add 'test' at the beginning
        rename 's/(.*)\.py/test $1.py/' *
        # rename the files so they are found by pytest: change spaces to underscores
        rename 's/ /_/g' test*
        # modify each file by adding one level of indentation to each line
        sed -i 's/^/    /' test*.py
        # modify each file by adding 'def test_func():' at the top
        sed -i '1s;^;def test_func():\n;' test*.py

    - name: Test tutorial notebooks
      run: |
        cd siamds2025
        # run pytest ONLY on the tutorials
        pytest --color=yes
